### ISSUE TITLE
[Question] Support npm

### ISSUE THREAD

**Issue by gabrieledarrigo** [sh7dm/vue-simple-icons#2]
Hi @sh7dm, should we support npm and add a package-lock.json file?
Another question, what version of node, npm and yarn are you using for iterating on this project?

**Comment by sh7dm** [comment]
@gabrieledarrigo I use Node v11.1.0 and yarn v1.12.3

**Comment by gabrieledarrigo** [comment]
Just created a pull request in order to support npm. Let me know what you think guys!

**Comment by ericcornelissen** [comment]
As far as I know you should use only a single package manager (whether we use _npm_ or _yarn_ doesn't matter to me). If we stick with _yarn_ as a package manger it should be documented in `CONTRIBUTING.md` (#4 relevant).

The reason there is a `package.json` but no `package-lock.json`, @gabrieledarrigo, is that _yarn_ uses `package.json` and we need it in order to publish to npm, but _yarn_ has its own lock format (in `yarn.lock`). We might consider switching form `yarn.lock` to `package-lock.json`, which yarn [supports since 1.7.0](https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/). A useful paragraph from this link:

> Currently, we’re planning to add some warnings to users who use both yarn and npm in the same repository to install packages. If there’s a need, we might also try to expand this feature to other lock file formats. If you’d like to point out other issues of interoperability, or try your hand at fixing them - we encourage you to file an issue or better, fix one by sending a PR.
We highly recommend you to delete the package-lock.json file if you decide to use yarn in order to avoid future confusion and possible consistency issues.

**Comment by gabrieledarrigo** [comment]
Ciao @ericcornelissen, thank you for coming in, make it totally sense, my bad!
Let's close the PR!

**Comment by ericcornelissen** [comment]
Your welcome @gabrieledarrigo, lets close the issue as well now we're all on the same page 👍
